" Inspired by
" https://dougblack.io/words/a-good-vimrc.html

set nocompatible
filetype plugin indent on

let g:solarized_termcolors=256
syntax enable
set background=light
colorscheme solarized

set tabstop=2
set softtabstop=2
set expandtab

set number
set showcmd
set cursorline

filetype indent on
set wildmenu
set lazyredraw
set showmatch

set incsearch
set hlsearch
nnoremap <leader><space> :nohlsearch<CR> " turn off search highlight

set foldenable
set foldlevelstart=10
set foldnestmax=10
nnoremap <space> za "space open/closes folds
set foldmethod=indent

" allows cursor change in tmux mode
if exists('$TMUS')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
end


set ignorecase
set ruler
set laststatus=2
set visualbell
set t_vb=
set mouse=a
set nostartofline
set nostartofline
set smartcase
set backspace=indent,eol,start
